from pathlib import Path

p = Path('.github/agent-presentation.py')
text = p.read_text()
old = '''old_camera = \'\'\'    const locked = cameraRef.current;\n    const camScale = locked ? 1 : Math.min(VIEW_WIDTH / game.worldWidth, VIEW_HEIGHT / game.worldHeight);\n    const camX = locked ? cap(VIEW_WIDTH / 2 - player.x, VIEW_WIDTH - game.worldWidth, 0) : (VIEW_WIDTH - game.worldWidth * camScale) / 2;\n    const camY = locked ? cap(VIEW_HEIGHT / 2 - player.y, VIEW_HEIGHT - game.worldHeight, 0) : (VIEW_HEIGHT - game.worldHeight * camScale) / 2;\n\'\'\'\nnew_camera = \'\'\'    const locked = cameraRef.current;\n    const camScale = locked ? ZOOM_SCALE[zoomRef.current] : Math.min(VIEW_WIDTH / game.worldWidth, VIEW_HEIGHT / game.worldHeight);\n    const camX = locked ? cap(VIEW_WIDTH / 2 - player.x * camScale, VIEW_WIDTH - game.worldWidth * camScale, 0) : (VIEW_WIDTH - game.worldWidth * camScale) / 2;\n    const camY = locked ? cap(VIEW_HEIGHT / 2 - player.y * camScale, VIEW_HEIGHT - game.worldHeight * camScale, 0) : (VIEW_HEIGHT - game.worldHeight * camScale) / 2;\n\'\'\'\ngame = Path("app/game.tsx").read_text()\nif game.count(old_camera) != 2:\n    raise SystemExit(f"expected two camera transforms, found {game.count(old_camera)}")\ngame = game.replace(old_camera, new_camera)\nPath("app/game.tsx").write_text(game)\n'''
new = '''game = Path("app/game.tsx").read_text()\ncamera_lines = [\n    (\n        "const camScale = locked ? 1 : Math.min(VIEW_WIDTH / game.worldWidth, VIEW_HEIGHT / game.worldHeight);",\n        "const camScale = locked ? ZOOM_SCALE[zoomRef.current] : Math.min(VIEW_WIDTH / game.worldWidth, VIEW_HEIGHT / game.worldHeight);",\n    ),\n    (\n        "const camX = locked ? cap(VIEW_WIDTH / 2 - player.x, VIEW_WIDTH - game.worldWidth, 0) : (VIEW_WIDTH - game.worldWidth * camScale) / 2;",\n        "const camX = locked ? cap(VIEW_WIDTH / 2 - player.x * camScale, VIEW_WIDTH - game.worldWidth * camScale, 0) : (VIEW_WIDTH - game.worldWidth * camScale) / 2;",\n    ),\n    (\n        "const camY = locked ? cap(VIEW_HEIGHT / 2 - player.y, VIEW_HEIGHT - game.worldHeight, 0) : (VIEW_HEIGHT - game.worldHeight * camScale) / 2;",\n        "const camY = locked ? cap(VIEW_HEIGHT / 2 - player.y * camScale, VIEW_HEIGHT - game.worldHeight * camScale, 0) : (VIEW_HEIGHT - game.worldHeight * camScale) / 2;",\n    ),\n]\nfor old_line, new_line in camera_lines:\n    if game.count(old_line) != 2:\n        raise SystemExit(f"expected two camera-line matches, found {game.count(old_line)}: {old_line}")\n    game = game.replace(old_line, new_line)\nPath("app/game.tsx").write_text(game)\n'''
if old not in text:
    raise SystemExit('camera helper block not found')
p.write_text(text.replace(old, new, 1))
Path('.github/fix-presentation-agent.py').unlink()
